# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM oven/bun:latest
WORKDIR /app

# Copy package files and install dependencies
COPY package.json ./
COPY tsconfig.json ./
COPY bun.lockb ./
RUN bun install --ignore-scripts

ENV MIXPANEL_USERNAME=
ENV MIXPANEL_PASSWORD=
ENV MIXPANEL_PROJECT_ID=
ENV PORT=3000
# Copy the rest of the source code and build
COPY . .
RUN bun run build

# Expose MCP default port if needed (MCP over stdio, so not exposing ports)
EXPOSE $PORT

# Default command: Expecting user to provide Mixpanel credentials
CMD ["bun", "build/index.js", "--transport", "sse", "--username", "$MIXPANEL_USERNAME", "--password", "$MIXPANEL_PASSWORD", "--projectId", "$MIXPANEL_PROJECT_ID"]
